version: '3.1'
services:
  web:
    build: .
    volumes:
      - .:/todo
    command: python -u app.py
    container_name: servidorWeb
    ports:
      - "80:80"


  db:
    image: mysql
    container_name: mysqlDB
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: P9
      MYSQL_USER: testuser
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./MySQL/database:/var/lib/mysql:rw
      

  # Names our volume
volumes:
  my-db:
