version: '3.1'
services:
  web:
    build: .
    volumes:
      - .:/todo
    command: python -u app.py
    ports:
      - "80:80"

  sonarqube:
      image: sonarqube:7.0
      container_name: sonarqube
      depends_on:
        - db
      command: -Dsonar.web.context=/sonarqube
      ports:
        - 9000:9000
        - 9092:9092
      environment:
        - SONAR_JDBC_USERNAME=sonar
        - SONAR_JDBC_PASSWORD=sonar
        - SONAR_JDBC_URL=jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8
      restart: always
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes: 
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
