version: '3.1'
services:
  web:
    build: .
    volumes:
      - .:/todo
    command: python -u app.py
    ports:
      - "80:80"

  sonarqube:
    image: sonarqube:5.1.1
    ports:
    - "9000:9000"
    - "3307:3307"
    environment:
    - SONARQUBE_JDBC_USERNAME=root
    - SONARQUBE_JDBC_PASSWORD=example
    - SONARQUBE_JDBC_URL=jdbc:mysql://34.72.13.19:3306/P8?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
