version: '3.1'
services:
  web:
    build: .
    volumes:
      - .:/todo
    command: python -u app.py
    ports:
      - "80:80"

  sonarqube:
      image: sonarqube:7.0
      container_name: sonarqube
      depends_on:
        - db
      command: -Dsonar.web.context=/sonarqube
      ports:
        - 9000:9000
        - 9092:9092
      environment:
        - SONAR_JDBC_USERNAME=sonar
        - SONAR_JDBC_PASSWORD=sonar
        - SONAR_JDBC_URL=jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8
      restart: always
  db:
    image: mysql
    container_name: mysqlDB
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: P9
      MYSQL_USER: testuser
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./MySQL/database:/var/lib/mysql:rw
      

  # Names our volume
volumes:
  my-db:
